name: testing_app
description: A sample that shows testing in Flutter.

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  golden_toolkit: ^0.15.0


  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  go_router: ">=10.0.0 <15.0.0"

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
  uses-material-design: true
