name: Golden Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-golden-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'

    # Step 3: Navigate to the testing_app folder
    - name: Navigate to Testing App Directory
      working-directory: ./testing_app
      run: echo "Navigating to the testing_app directory"

    # Step 4: Install Dependencies
    - name: Install Dependencies
      working-directory: ./testing_app
      run: flutter pub get

    # Step 5: Ensure Golden Files Directory Exists
    - name: Create Golden Files Directory
      working-directory: ./testing_app
      run: mkdir -p test/golden_images

    # Step 6: Run Golden Tests
    - name: Run Golden Tests
      working-directory: ./testing_app
      run: flutter test --update-goldens --verbose

    # Step 7: Debug Golden Files Generation
    - name: Debug Golden Files
      working-directory: ./testing_app
      run: ls -R test/golden_images

      
    # Step 8: Upload Files to Percy
    - name: Upload Golden Files to Percy
      working-directory: ./testing_app
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      run: |
        # Install Percy CLI
        npm install -g @percy/cli
        # Upload golden files to Percy
        percy upload ./test/golden_images/
