name: Golden Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-golden-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'

    # Step 3: Navigate to the testing_app folder
    - name: Navigate to Testing App Directory
      working-directory: ./testing_app
      run: echo "Navigating to the testing_app directory"

    # Step 4: Install Dependencies
    - name: Install Dependencies
      working-directory: ./testing_app
      run: flutter pub get

    # Step 5: Run Golden Tests
    - name: Run Golden Tests
      working-directory: ./testing_app
      run: flutter test --update-goldens
